AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Sample Template DocumentDB_Quick_Create with SSM SecureString reference."

Parameters: 
  DBClusterName: 
    Default: "MyCluster"
    Description: "Cluster name"
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*(-[a-zA-Z0-9]+)*"
    ConstraintDescription: "Must begin with a letter and contain only alphanumeric characters."

  DBInstanceName: 
    Default: "MyInstance"
    Description: "Instance name"
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*(-[a-zA-Z0-9]+)*"
    ConstraintDescription: "Must begin with a letter and contain only alphanumeric characters."

  DBInstanceClass:
    Description: "Instance class. Refer to the DocumentDB DB instance classes by region."
    Type: String
    AllowedValues:
      - db.t3.medium
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.12xlarge
      - db.r5.24xlarge
    ConstraintDescription: "Must be a valid DocumentDB instance class."

  # New parameters that reference the existing SecureString parameters in SSM
  MasterUserParameterName:
    Description: "Name (path) of the SSM SecureString parameter that stores the master username."
    Type: String
    Default: "/myDocDB/masterUser"

  MasterPasswordParameterName:
    Description: "Name (path) of the SSM SecureString parameter that stores the master password."
    Type: String
    Default: "/myDocDB/masterPassword"

Resources:
  DBCluster:
    Type: "AWS::DocDB::DBCluster"
    DeletionPolicy: Delete
    Properties:
      DBClusterIdentifier: !Ref DBClusterName

      # Dynamically resolve master username/password from SSM SecureString
      MasterUsername: !Sub "{{resolve:ssm-secure:${MasterUserParameterName}}}"
      MasterUserPassword: !Sub "{{resolve:ssm-secure:${MasterPasswordParameterName}}}"

      EngineVersion: "4.0.0"

  DBInstance:
    Type: "AWS::DocDB::DBInstance"
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceIdentifier: !Ref DBInstanceName
      DBInstanceClass: !Ref DBInstanceClass
    DependsOn: DBCluster

Outputs:
  ClusterId:
    Description: "The identifier of the DocumentDB cluster"
    Value: !Ref DBCluster

  ClusterEndpoint:
    Description: "The endpoint for the DocumentDB cluster"
    Value: !GetAtt DBCluster.Endpoint

  ClusterPort:
    Description: "The port for the DocumentDB cluster"
    Value: !GetAtt DBCluster.Port

  EngineVersion:
    Description: "DocumentDB engine version used"
    Value: "4.0.0"