name: CI/CD Pipeline for Ticket Booking System

on:
  push:
    branches:
      - aws-dev  # listen to aws-dev branch push

jobs:
  build:
    runs-on: ubuntu-latest # GitHub hosted Ubuntu server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # pull GitHub code

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean package  # run Maven build

      - name: Run Tests
        run: mvn test  # run mvn test

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ticket-booking .
          docker tag ticket-booking:latest ${{ secrets.ECR_REPO }}:latest
          docker push ${{ secrets.ECR_REPO }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Configure Kubernetes
        run: aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy to EKS
        run: kubectl apply -f k8s/deployment.yaml
