name: Deploy Seat Reservation Lambda Stack

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: "Select branch to deploy"
        required: true
        default: "master"

jobs:
  info:
    name: Info
    runs-on: ubuntu-latest
    steps:
      - name: workflow details
        run: |
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Git Branch: ${{ github.ref }}"
          echo "Git SHA: ${{ github.sha }}"
          echo "Github Event: ${{ github.event_name }}"

  deploy:
    name: Deploy AWS CDK Stack
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation Stack
        run: |
            aws cloudformation deploy \
              --stack-name documentdb \
              --template-file documentdb/stack.yml \
              --capabilities CAPABILITY_IAM